services:
  - type: web
    name: social-media-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/testApp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: DATABASE_URL
        value: jdbc:postgresql://ep-green-fire-a1zakmwx-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
      - key: DATABASE_USERNAME
        value: neondb_owner
      - key: DATABASE_PASSWORD
        value: npg_QBMC6f2nSrDP
      - key: SHOW_SQL
        value: false
    healthCheckPath: /login

