services:
  - type: web
    name: social-media-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/testApp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: DATABASE_URL
        value: jdbc:postgresql://bugwe0.h.filess.io:61006/social_keeptaxarm
      - key: DATABASE_USERNAME
        value: social_keeptaxarm
      - key: DATABASE_PASSWORD
        value: 767f6876cce8411d4666b3239109607e08e1ee4d
      - key: SHOW_SQL
        value: false
    healthCheckPath: /login

